### PR TITLE
Fix a typo in the quote attribution

### PR DESCRIPTION
**Pull request by Greyvy**
Changed “...nnes Ittem...” to “...nnes Itten”

### CODE REVIEW

**Comment by runemadsen** [comment]
@Greyvy 👍  These are the PR's I like the most :)

**Comment by Greyvy** [comment]
Happy to help in any little way. Love, love, love the book so far, an extremely interesting subject to me with few and difficult to find resources. Thanks!

**Comment by runemadsen** [comment]
That's great to hear. Let me know if you find other edits!

**Comment by Greyvy** [comment]
Will do

**Pull request merged**
